version: '3.7'
services:

 api:
     build: .
     image: "myapi"
     hostname: "myapi"
     ports:
         - "8080:8080"
     networks:
             - iot-labs
     labels:
           NAME: "myapi"

networks:
   iot-labs:
       external: true
